#!/usr/bin/env python3
"""
Example script demonstrating the crypto LLM analyst system.
This script shows how to use all the major components together.
"""

import asyncio
import logging
import os
from datetime import datetime, timedelta

# Add src to path for imports
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from crypto_llm_analyst.main import CryptoLLMAnalyst, load_config_from_env

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def example_basic_usage():
    """Basic usage example."""
    logger.info("=== Basic Usage Example ===")
    
    # Load configuration from environment
    config = load_config_from_env()
    
    # For demo purposes, you can override with dummy values if env vars not set
    if not config.get("openai_api_key"):
        logger.warning("OpenAI API key not found, using dummy key for demo")
        config["openai_api_key"] = "sk-dummy-key-for-demo"
    
    # Initialize system
    system = CryptoLLMAnalyst(config)
    
    try:
        # Initialize components
        success = await system.initialize()
        if not success:
            logger.error("Failed to initialize system")
            return
        
        # Check system status
        status = system.get_system_status()
        logger.info(f"System Status: {status}")
        
        # Example: Get market summary (requires database)
        if system.database:
            logger.info("Getting market summary...")
            summary = await system.get_market_summary("BTCUSDT")
            logger.info(f"Market Summary: {summary}")
        else:
            logger.info("Database not available, skipping market summary")
        
        # Example: Perform analysis (requires LLM)
        if system.llm_manager:
            logger.info("Performing market analysis...")
            analysis = await system.analyze_market(
                symbol="BTCUSDT",
                query="What is the current trend for Bitcoin?",
                analysis_type="general"
            )
            logger.info(f"Analysis Result: {analysis.get('analysis', 'No analysis available')[:200]}...")
        else:
            logger.info("LLM manager not available, skipping analysis")
        
    finally:
        await system.shutdown()


async def example_data_streaming():
    """Data streaming example."""
    logger.info("=== Data Streaming Example ===")
    
    config = load_config_from_env()
    
    # Override for demo
    if not config.get("bitquery_api_key"):
        logger.warning("Bitquery API key not found, skipping streaming example")
        return
    
    system = CryptoLLMAnalyst(config)
    
    try:
        await system.initialize()
        
        # Start data streaming
        logger.info("Starting data streaming...")
        streaming_started = await system.start_data_streaming()
        
        if streaming_started:
            logger.info("Data streaming active for 30 seconds...")
            await asyncio.sleep(30)
            logger.info("Stopping data streaming...")
        else:
            logger.info("Failed to start data streaming")
        
    finally:
        await system.shutdown()


async def example_rag_system():
    """RAG system example."""
    logger.info("=== RAG System Example ===")
    
    config = load_config_from_env()
    
    if not config.get("openai_api_key"):
        logger.warning("OpenAI API key required for RAG example")
        return
    
    system = CryptoLLMAnalyst(config)
    
    try:
        await system.initialize()
        
        if not system.rag_system:
            logger.info("RAG system not initialized")
            return
        
        # Index some sample knowledge
        sample_knowledge = [
            """
            Bitcoin (BTC) is the first and largest cryptocurrency by market capitalization.
            It was created by Satoshi Nakamoto in 2009 as a peer-to-peer electronic cash system.
            Bitcoin operates on a proof-of-work consensus mechanism and has a maximum supply of 21 million coins.
            """,
            """
            Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity.
            Common technical indicators include moving averages, RSI, MACD, and Bollinger Bands.
            Support and resistance levels are key concepts in technical analysis.
            """,
            """
            Market sentiment refers to the overall attitude of investors toward a particular market or security.
            Sentiment can be bullish (positive) or bearish (negative).
            News events, economic data, and social media can all influence market sentiment.
            """
        ]
        
        # Index the knowledge
        logger.info("Indexing sample knowledge...")
        indexed_count = await system.rag_system.index_market_knowledge(
            sample_knowledge,
            [
                {"topic": "bitcoin_basics", "category": "cryptocurrency"},
                {"topic": "technical_analysis", "category": "trading"},
                {"topic": "market_sentiment", "category": "psychology"}
            ]
        )
        logger.info(f"Indexed {indexed_count} knowledge documents")
        
        # Retrieve relevant context
        logger.info("Retrieving context for Bitcoin analysis...")
        context = await system.rag_system.get_market_context(
            "What should I know about Bitcoin trading?",
            time_range_hours=24
        )
        logger.info(f"Retrieved context: {context[:300]}...")
        
    finally:
        await system.shutdown()


async def example_mcp_protocol():
    """MCP protocol example."""
    logger.info("=== MCP Protocol Example ===")
    
    config = load_config_from_env()
    system = CryptoLLMAnalyst(config)
    
    try:
        await system.initialize()
        
        if not system.mcp_protocol:
            logger.info("MCP protocol not initialized")
            return
        
        # Example MCP messages
        initialize_request = {
            "id": "req_001",
            "type": "request",
            "method": "initialize",
            "params": {}
        }
        
        list_tools_request = {
            "id": "req_002",
            "type": "request",
            "method": "list_tools",
            "params": {}
        }
        
        # Handle messages
        logger.info("Sending MCP initialize request...")
        init_response = await system.mcp_protocol.handle_message(initialize_request)
        logger.info(f"Initialize response: {init_response}")
        
        logger.info("Sending list tools request...")
        tools_response = await system.mcp_protocol.handle_message(list_tools_request)
        logger.info(f"Available tools: {len(tools_response.get('result', {}).get('tools', []))}")
        
    finally:
        await system.shutdown()


async def example_n8n_workflows():
    """N8N workflows example."""
    logger.info("=== N8N Workflows Example ===")
    
    config = load_config_from_env()
    
    if not config.get("n8n_url"):
        logger.warning("N8N URL not configured, skipping N8N example")
        return
    
    system = CryptoLLMAnalyst(config)
    
    try:
        await system.initialize()
        
        if not system.n8n_manager:
            logger.info("N8N manager not initialized")
            return
        
        # Setup workflows
        logger.info("Setting up N8N workflows...")
        success = await system.setup_n8n_workflows()
        
        if success:
            logger.info("✅ N8N workflows created successfully")
            
            # Example webhook trigger
            logger.info("Triggering analysis workflow...")
            async with system.n8n_manager:
                result = await system.n8n_manager.webhook_trigger(
                    "webhook/crypto-analysis",
                    {
                        "symbol": "BTCUSDT",
                        "query": "What's the market sentiment?"
                    }
                )
                logger.info(f"Webhook result: {result}")
        else:
            logger.info("❌ Failed to create N8N workflows")
        
    finally:
        await system.shutdown()


async def example_comprehensive_analysis():
    """Comprehensive analysis example using multiple components."""
    logger.info("=== Comprehensive Analysis Example ===")
    
    config = load_config_from_env()
    system = CryptoLLMAnalyst(config)
    
    try:
        await system.initialize()
        
        # Perform different types of analysis
        analyses = [
            ("general", "What is the overall market sentiment for Bitcoin?"),
            ("technical", "What do the technical indicators show for BTCUSDT?"),
            ("prediction", "Where do you see Bitcoin price in the next 24 hours?"),
            ("market", "Should I buy, sell, or hold Bitcoin right now?")
        ]
        
        for analysis_type, query in analyses:
            if system.llm_manager:
                logger.info(f"Performing {analysis_type} analysis...")
                result = await system.analyze_market(
                    symbol="BTCUSDT",
                    query=query,
                    analysis_type=analysis_type
                )
                
                logger.info(f"{analysis_type.title()} Analysis:")
                logger.info(f"  Query: {query}")
                logger.info(f"  Confidence: {result.get('confidence', 0):.1%}")
                logger.info(f"  Result: {result.get('analysis', 'No result')[:150]}...")
                logger.info("")
            else:
                logger.info(f"Skipping {analysis_type} analysis (LLM not available)")
        
    finally:
        await system.shutdown()


async def main():
    """Run all examples."""
    examples = [
        ("Basic Usage", example_basic_usage),
        ("RAG System", example_rag_system),
        ("MCP Protocol", example_mcp_protocol),
        ("Comprehensive Analysis", example_comprehensive_analysis),
        # Note: These require external services
        # ("Data Streaming", example_data_streaming),
        # ("N8N Workflows", example_n8n_workflows),
    ]
    
    for name, example_func in examples:
        try:
            logger.info(f"\n{'='*60}")
            logger.info(f"Running: {name}")
            logger.info('='*60)
            await example_func()
            await asyncio.sleep(1)  # Brief pause between examples
        except Exception as e:
            logger.error(f"Error in {name}: {e}")
    
    logger.info("\n🎉 All examples completed!")


if __name__ == "__main__":
    print("🚀 Crypto LLM Analyst Examples")
    print("=" * 50)
    print("This script demonstrates the various features of the crypto LLM analyst system.")
    print("Make sure to set your API keys as environment variables:")
    print("  - OPENAI_API_KEY (required for LLM and RAG)")
    print("  - BITQUERY_API_KEY (required for data streaming)")
    print("  - SUPABASE_URL and SUPABASE_KEY (required for database)")
    print("  - N8N_URL (required for workflow automation)")
    print()
    
    asyncio.run(main())